### References

https://github.com/gabrielziegler3/xgboost-multiclass-multilabel/blob/master/xgboost-multiclass/multiclass-frog-classification.ipynb

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import glob

In [2]:
all_files = glob.glob("../ml_cp18/ml_cp18*.csv")
data = pd.concat((pd.read_csv(f) for f in all_files))
data

,bid_size,ask_size,last_size,volume,bid_ask_delta,c_w1_p3_bid_ask_delta,c_w1_p3_ask_size,c_w1_p3_bid_size,c_w1_p3_last_size,c_w1_p3_theta,...,c_w3_p2_ask,c_w3_p2_bid,c_w3_p2_last,c_w3_p2_strike_delta,c_w3_p2_time_value,c_w3_p3_ask,c_w3_p3_bid,c_w3_p3_last,c_w3_p3_strike_delta,c_w3_p3_time_value
0,19.0,2.0,2.0,695172.0,-0.01,-0.02,196.0,300.0,5.0,4.218534,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,13.0,8.0,1.0,695178.0,-0.01,-0.01,162.0,10.0,1.0,3.404795,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,27.0,3.0,3.0,695182.0,-0.01,-0.02,246.0,308.0,1.0,3.402490,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,24.0,3.0,1.0,695870.0,-0.01,-0.01,267.0,23.0,5.0,4.220839,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,21.0,2.0,695873.0,-0.01,-0.02,267.0,278.0,5.0,4.218534,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23237,2.0,6.0,1.0,1026554.0,-0.09,-1.01,3773.0,0.0,20.0,8425.000000,...,2.80,2.74,2.8,-3.05,5.82,1.89,1.84,1.89,-5.55,7.415
23238,6.0,15.0,1.0,1026562.0,-0.05,-1.01,3630.0,0.0,20.0,8408.333333,...,2.81,2.71,2.8,-3.04,5.80,1.89,1.76,1.89,-5.54,7.365
23239,218.0,39.0,29.0,1026592.0,-0.07,-1.01,3558.0,0.0,20.0,8491.666667,...,2.85,2.61,2.8,-3.09,5.82,1.89,1.76,1.89,-5.59,7.415
23240,175.0,1.0,1.0,1026594.0,-0.01,-1.01,3512.0,0.0,20.0,8591.666667,...,2.85,2.61,2.8,-3.15,5.88,1.89,1.76,1.86,-5.65,7.475
23241,140.0,135.0,4.0,1026599.0,-0.01,0.00,0.0,0.0,20.0,0.000000,...,-1.00,-1.00,2.8,-3.16,2.16,-1.00,-1.00,1.86,-5.66,4.660

In [3]:
data = data.dropna()
#data = data.head(1000)
data

,bid_size,ask_size,last_size,volume,bid_ask_delta,c_w1_p3_bid_ask_delta,c_w1_p3_ask_size,c_w1_p3_bid_size,c_w1_p3_last_size,c_w1_p3_theta,...,c_w3_p2_ask,c_w3_p2_bid,c_w3_p2_last,c_w3_p2_strike_delta,c_w3_p2_time_value,c_w3_p3_ask,c_w3_p3_bid,c_w3_p3_last,c_w3_p3_strike_delta,c_w3_p3_time_value
1217,6.0,409.0,10.0,114750.0,-0.01,-0.01,2883.0,1100.0,2.0,27.830189,...,2.37,2.36,2.36,-3.66,6.025,1.56,1.55,1.56,-6.16,7.715
1218,8.0,27.0,1.0,114752.0,-0.01,-0.01,2128.0,608.0,2.0,28.414196,...,2.32,2.31,2.31,-3.79,6.105,1.53,1.52,1.55,-6.29,7.815
1219,13.0,19.0,1.0,114754.0,-0.02,-0.01,3638.0,323.0,2.0,28.504043,...,2.32,2.31,2.31,-3.81,6.125,1.53,1.52,1.52,-6.31,7.835
1220,5.0,1.0,2.0,114757.0,-0.01,-0.01,1998.0,318.0,2.0,28.593890,...,2.32,2.30,2.31,-3.83,6.140,1.53,1.51,1.51,-6.33,7.850
1221,2.0,25.0,10.0,114772.0,-0.02,-0.01,3184.0,340.0,6.0,28.369272,...,2.34,2.32,2.31,-3.78,6.110,1.54,1.52,1.51,-6.28,7.810
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23237,2.0,6.0,1.0,1026554.0,-0.09,-1.01,3773.0,0.0,20.0,8425.000000,...,2.80,2.74,2.80,-3.05,5.820,1.89,1.84,1.89,-5.55,7.415
23238,6.0,15.0,1.0,1026562.0,-0.05,-1.01,3630.0,0.0,20.0,8408.333333,...,2.81,2.71,2.80,-3.04,5.800,1.89,1.76,1.89,-5.54,7.365
23239,218.0,39.0,29.0,1026592.0,-0.07,-1.01,3558.0,0.0,20.0,8491.666667,...,2.85,2.61,2.80,-3.09,5.820,1.89,1.76,1.89,-5.59,7.415
23240,175.0,1.0,1.0,1026594.0,-0.01,-1.01,3512.0,0.0,20.0,8591.666667,...,2.85,2.61,2.80,-3.15,5.880,1.89,1.76,1.86,-5.65,7.475
23241,140.0,135.0,4.0,1026599.0,-0.01,0.00,0.0,0.0,20.0,0.000000,...,-1.00,-1.00,2.80,-3.16,2.160,-1.00,-1.00,1.86,-5.66,4.660

In [ ]:
X = data.drop(['p60s_bucket_category', 'p300s_bucket_category'], axis=1)
Y = data[['p300s_bucket_category']]

In [ ]:
categories = Y.p300s_bucket_category.unique().tolist()

In [ ]:
from sklearn.model_selection import train_test_split
X15_train, X15_test, y15_train, y15_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
from datetime import datetime
from sklearn.model_selection import GridSearchCV
import xgboost as xgb
from xgboost.sklearn import XGBClassifier

start_time = datetime.now()
# From Sagemaker tuning
parameters = {'_kfold': '5',
              '_tuning_objective_metric': 'validation:accuracy',
              'objective': 'validation:accuracy',
              
              'alpha': 0.029064625217569095,
              'colsample_bytree': 0.5300674649920706,
              'eta': 0.06785230577839381,
              'eval_metric': 'accuracy,f1',
              'gamma': 8.822571607235765e-06,
              'lambda': 2.236266181542945e-06,
              'max_depth': 8,
              'min_child_weight': 5.3334410483799005e-05,
              'num_class': 9,
              'num_round': 855,
              'objective': 'multi:softprob',
              'subsample': 0.7607022674051444}

xgb15 = XGBClassifier(objective='multi:softprob', eval_metric='merror',
            gamma=0.000008822571607235765, #8.822571607235765e-06,
            min_child_weight=5.3334410483799005e-05,
            num_class=7,
            #'lambda'=0.000002236266181542945, #2.236266181542945e-06,
            max_depth=8
)

xgb15.fit(X15_train, y15_train)

stop_time = datetime.now()

In [ ]:
print('Start Timestamp : ', start_time.strftime("%d-%b-%Y (%H:%M:%S.%f)"))
print('Stop Timestamp : ', stop_time.strftime("%d-%b-%Y (%H:%M:%S.%f)"))
import math
td = stop_time - start_time
td_mins = int(math.floor((td).total_seconds() / 60))
td_secs = td.total_seconds() - int(math.floor((td).total_seconds() / 60)*60)
print(f'The difference is approx. {td_mins}:{td_secs:02.0f} (min:sec)')

In [ ]:
pred = xgb15.predict(X15_test)

from sklearn.metrics import accuracy_score
print(accuracy_score( y15_test, pred ) )

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y15_test, pred, target_names=categories))

In [ ]:
def plot_confusion_matrix(cm, classes, normalized=True, cmap='bone', fmt='g'):
    plt.figure(figsize=[7, 6])
    norm_cm = cm
    if normalized:
        norm_cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        sns.heatmap(norm_cm, annot=cm, fmt=fmt, xticklabels=classes, yticklabels=classes, cmap=cmap)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pylab as plt
import seaborn as sns
import xgboost as xgb

frog_cm = confusion_matrix(y15_test, pred)
plot_confusion_matrix(frog_cm, classes=categories, cmap='YlGnBu')

In [ ]:
frog_cm_pct = frog_cm.astype('float') / frog_cm.sum(axis=1)[:, np.newaxis]

In [ ]:
plot_confusion_matrix(frog_cm_pct, fmt='.2f', cmap='YlGnBu', classes=categories)

In [ ]:
file="models/dec21-xgboost" +  datetime.now().strftime("-%Y%m%d-%H%M%S") +".txt"
xgb15.save_model(file)
file